---
title: "Inspire"
author: "Soo Wan Kim"
date: "April 25, 2017"
output:
  html_document:
    code_folding: hide
    keep_md: true
    theme: default
---

```{r setup}
library(tidyverse)
library(knitr)

issues <- read.csv("Data/inspire_issues.csv") %>%
  rename(Issue = `ï..Issue`)

cat <- read.csv("Data/inspire_catalogue.csv") %>%
  rename(Issue = `ï..Issue`) %>%
  transform(Issue = as.double(Issue)) %>%
  transform(NumPages = as.double(NumPages)) %>%
  transform(ItemType = as.character(ItemType)) %>%
  transform(ItemType = ifelse(ItemType %in% c("Poetry", "Photography"), "Art and Poetry", ItemType)) %>%
  transform(ItemType = as.factor(ItemType))
  
cat_type <- cat %>%
  group_by(ItemType) %>%
  summarize(SumPages = sum(NumPages)) %>%
  arrange(SumPages)

cat$ItemType <- factor(cat$ItemType, levels(cat$ItemType)[cat_type$ItemType])

cat_issue_type <- cat %>%
  group_by(Issue, ItemType) %>%
  summarize(SumPages = sum(NumPages)) %>%
  ungroup()

find_missing_type <- function(issue) {
  data = dplyr::filter(cat_issue_type, Issue == issue)
  TypeList = data$ItemType
  missing = cat_type$ItemType[!cat_type$ItemType %in% TypeList]
  
  return(missing)
}

make_row <- function(issue, missing_type) {
  row = t(as_tibble(c(issue, missing_type, 0)))
  colnames(row) <- c("Issue", "ItemType", "SumPages")
  row = as.data.frame(row)
  rownames(row) <- NULL
  return(row)
}

make_rows <- function(issue) {
  missing = find_missing_type(issue)
  missing_rows = make_row(issue, as.character(missing[1]))
  if (length(missing) > 1) {
    for (x in tail(missing, -1)) {
    missing_rows = rbind(missing_rows, make_row(issue, as.character(x)))
    }
  }
  else {
    missing_rows = missing_rows
  }
  
  return(missing_rows)
}

missing_rows <- make_rows(1)
for (x in seq(2,16)) {
  missing_rows <- rbind(missing_rows, make_rows(x))
}

missing_rows <- missing_rows %>%
  transform(Issue = as.numeric(Issue)) %>%
  transform(SumPages = as.numeric(SumPages) - 1)

cat_issue_type <- rbind(cat_issue_type, missing_rows) %>%
  arrange(Issue) %>%
  na.omit()

TotPages <- cat %>%
  group_by(Issue) %>%
  summarize(TotalPages = sum(NumPages))

cat_issue_type <- left_join(cat_issue_type, TotPages) %>%
  mutate(SharePages = SumPages/TotalPages)

rep1 <- cat_issue_type %>%
  filter(Issue < 16) %>%
  transform(Issue = Issue + 0.5)

rep2 <- cat_issue_type %>%
  filter(Issue < 16) %>%
  transform(Issue = Issue + 0.9)

cat_join <- rbind(cat_issue_type, rbind(rep1, rep2))

#how to make timeline
#https://www.r-bloggers.com/timeline-graph-with-ggplot2/
#http://stackoverflow.com/questions/7492274/draw-a-chronological-timeline-with-ggplot2
#http://jason.bryer.org/timeline/
#http://www.statsblogs.com/2012/07/07/timeline-graph-with-ggplot2/  
  
ggplot(filter(cat_join, Issue < 2),
       aes(Issue, SumPages, fill = ItemType)) + 
  geom_area() + 
  scale_x_continuous(breaks = seq(1,16,1))
  
ggplot(cat_issue_type, aes(x=Issue, y=SumPages, fill=ItemType)) + 
  geom_area() + 
  scale_x_continuous(breaks = seq(1, 16, 1))

ggplot(cat_issue_type, aes(x=Issue, y=SharePages, fill=ItemType)) + 
  geom_area(color = "black") + 
  scale_x_continuous(breaks = seq(1, 16, 1))

ggplot(cat_join, aes(x=Issue, y=SharePages, fill=ItemType)) + 
  geom_area() + 
  scale_x_continuous(breaks = seq(1, 16, 1))

cat_join$ItemType <- factor(cat_join$ItemType, levels = cat_type$ItemType)

x = 6
ggplot(filter(cat_join, Issue == x), 
       aes(ItemType, SharePages, fill=ItemType)) + 
  geom_bar(stat="identity") + 
  coord_flip()
#reverse order of legend

cat_type <- cat_type %>%
  mutate(Issue = 1) %>%
  mutate(Share = SumPages/sum(SumPages))

cat_type$ItemType <- factor(cat_type$ItemType, levels = cat_type$ItemType)

cat_type2 <- cat_type %>%
  transform(Issue = 1.999)

cat_type <- rbind(cat_type, cat_type2)

ggplot(filter(cat_type, Issue < 2), 
       aes(x=Issue, y=Share, fill=ItemType)) + 
  geom_area(color = "black")
```

```{r}
#timeline stuff
#https://daattali.com/shiny/timevis-demo/
#https://github.com/pachamaltese/bowie-timeline
#http://ramnathv.github.io/rCharts/
#http://stackoverflow.com/questions/20695311/chronological-timeline-with-points-in-time-and-format-date
#https://www.packtpub.com/mapt/book/big-data-and-business-intelligence/9781783989508/2/ch02lvl1sec34/generating-an-interactive-gantt/timeline-chart-in-r

```

